server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: lora-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lora}
    username: ${SPRING_DATASOURCE_USERNAME:lora}
    password: ${SPRING_DATASOURCE_PASSWORD:lora}
    driver-class-name: org.postgresql.Driver

